site_name: PGraf Cypher
site_description: Neo4j Cypher to PostgreSQL SQL translator for graph data
site_author: Gavin M. Roy
site_url: https://gmr.github.io/slack-models/

repo_name: gmr/slack-models
repo_url: https://github.com/gmr/slack-models
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src/slack_models]
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true
            show_bases: true
            heading_level: 2

nav:
  - Home: index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gmr/slack-models
      name: slack-models on GitHub
